export enum CountryCodes {
  AFGHANISTAN = 'AFG',
  ALBANIA = 'ALB',
  ALGERIA = 'DZA',
  AMERICAN_SAMOA = 'ASM',
  ANDORRA = 'AND',
  ANGOLA = 'AGO',
  ANGUILLA = 'AIA',
  ANTARCTICA = 'ATA',
  ANTIGUA_AND_BARBUDA = 'ATG',
  ARGENTINA = 'ARG',
  ARMENIA = 'ARM',
  ARUBA = 'ABW',
  AUSTRALIA = 'AUS',
  AUSTRIA = 'AUT',
  AZERBAIJAN = 'AZE',
  BAHAMAS = 'BHS',
  BAHRAIN = 'BHR',
  BANGLADESH = 'BGD',
  BARBADOS = 'BRB',
  BELARUS = 'BLR',
  BELGIUM = 'BEL',
  BELIZE = 'BLZ',
  BENIN = 'BEN',
  BERMUDA = 'BMU',
  BHUTAN = 'BTN',
  BOLIVIA_PLURINATIONAL_STATE_OF = 'BOL',
  BONAIRE_SINT_EUSTATIUS_AND_SABA = 'BES',
  BOSNIA_AND_HERZEGOVINA = 'BIH',
  BOTSWANA = 'BWA',
  BOUVET_ISLAND = 'BVT',
  BRAZIL = 'BRA',
  BRITISH_INDIAN_OCEAN_TERRITORY = 'IOT',
  BRUNEI_DARUSSALAM = 'BRN',
  BULGARIA = 'BGR',
  BURKINA_FASO = 'BFA',
  BURUNDI = 'BDI',
  CABO_VERDE = 'CPV',
  CAMBODIA = 'KHM',
  CAMEROON = 'CMR',
  CANADA = 'CAN',
  CAYMAN_ISLANDS = 'CYM',
  CENTRAL_AFRICAN_REPUBLIC = 'CAF',
  CHAD = 'TCD',
  CHILE = 'CHL',
  CHINA = 'CHN',
  CHRISTMAS_ISLAND = 'CXR',
  COCOS_KEELING_ISLANDS = 'CCK',
  COLOMBIA = 'COL',
  COMOROS = 'COM',
  CONGO = 'COG',
  CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE = 'COD',
  COOK_ISLANDS = 'COK',
  COSTA_RICA = 'CRI',
  CROATIA = 'HRV',
  CUBA = 'CUB',
  CURACAO = 'CUW',
  CYPRUS = 'CYP',
  CZECHIA = 'CZE',
  COTE_DIVOIRE = 'CIV',
  DENMARK = 'DNK',
  DJIBOUTI = 'DJI',
  DOMINICA = 'DMA',
  DOMINICAN_REPUBLIC = 'DOM',
  ECUADOR = 'ECU',
  EGYPT = 'EGY',
  EL_SALVADOR = 'SLV',
  EQUATORIAL_GUINEA = 'GNQ',
  ERITREA = 'ERI',
  ESTONIA = 'EST',
  ESWATINI = 'SWZ',
  ETHIOPIA = 'ETH',
  FALKLAND_ISLANDS_MALVINAS = 'FLK',
  FAROE_ISLANDS = 'FRO',
  FIJI = 'FJI',
  FINLAND = 'FIN',
  FRANCE = 'FRA',
  FRENCH_GUIANA = 'GUF',
  FRENCH_POLYNESIA = 'PYF',
  FRENCH_SOUTHERN_TERRITORIES = 'ATF',
  GABON = 'GAB',
  GAMBIA = 'GMB',
  GEORGIA = 'GEO',
  GERMANY = 'DEU',
  GHANA = 'GHA',
  GIBRALTAR = 'GIB',
  GREECE = 'GRC',
  GREENLAND = 'GRL',
  GRENADA = 'GRD',
  GUADELOUPE = 'GLP',
  GUAM = 'GUM',
  GUATEMALA = 'GTM',
  GUERNSEY = 'GGY',
  GUINEA = 'GIN',
  GUINEA_BISSAU = 'GNB',
  GUYANA = 'GUY',
  HAITI = 'HTI',
  HEARD_ISLAND_AND_MCDONALD_ISLANDS = 'HMD',
  HOLY_SEE_VATICAN_CITY_STATE = 'VAT',
  HONDURAS = 'HND',
  HONG_KONG = 'HKG',
  HUNGARY = 'HUN',
  ICELAND = 'ISL',
  INDIA = 'IND',
  INDONESIA = 'IDN',
  IRAN_ISLAMIC_REPUBLIC_OF = 'IRN',
  IRAQ = 'IRQ',
  IRELAND = 'IRL',
  ISLE_OF_MAN = 'IMN',
  ISRAEL = 'ISR',
  ITALY = 'ITA',
  JAMAICA = 'JAM',
  JAPAN = 'JPN',
  JERSEY = 'JEY',
  JORDAN = 'JOR',
  KAZAKHSTAN = 'KAZ',
  KENYA = 'KEN',
  KIRIBATI = 'KIR',
  KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF = 'PRK',
  KOREA_REPUBLIC_OF = 'KOR',
  KUWAIT = 'KWT',
  KYRGYZSTAN = 'KGZ',
  LAO_PEOPLES_DEMOCRATIC_REPUBLIC = 'LAO',
  LATVIA = 'LVA',
  LEBANON = 'LBN',
  LESOTHO = 'LSO',
  LIBERIA = 'LBR',
  LIBYA = 'LBY',
  LIECHTENSTEIN = 'LIE',
  LITHUANIA = 'LTU',
  LUXEMBOURG = 'LUX',
  MACAO = 'MAC',
  MADAGASCAR = 'MDG',
  MALAWI = 'MWI',
  MALAYSIA = 'MYS',
  MALDIVES = 'MDV',
  MALI = 'MLI',
  MALTA = 'MLT',
  MARSHALL_ISLANDS = 'MHL',
  MARTINIQUE = 'MTQ',
  MAURITANIA = 'MRT',
  MAURITIUS = 'MUS',
  MAYOTTE = 'MYT',
  MEXICO = 'MEX',
  MICRONESIA_FEDERATED_STATES_OF = 'FSM',
  MOLDOVA_REPUBLIC_OF = 'MDA',
  MONACO = 'MCO',
  MONGOLIA = 'MNG',
  MONTENEGRO = 'MNE',
  MONTSERRAT = 'MSR',
  MOROCCO = 'MAR',
  MOZAMBIQUE = 'MOZ',
  MYANMAR = 'MMR',
  NAMIBIA = 'NAM',
  NAURU = 'NRU',
  NEPAL = 'NPL',
  NETHERLANDS = 'NLD',
  NEW_CALEDONIA = 'NCL',
  NEW_ZEALAND = 'NZL',
  NICARAGUA = 'NIC',
  NIGER = 'NER',
  NIGERIA = 'NGA',
  NIUE = 'NIU',
  NORFOLK_ISLAND = 'NFK',
  NORTHERN_MARIANA_ISLANDS = 'MNP',
  NORTH_MACEDONIA = 'MKD',
  NORWAY = 'NOR',
  OMAN = 'OMN',
  PAKISTAN = 'PAK',
  PALAU = 'PLW',
  PALESTINE_STATE_OF = 'PSE',
  PANAMA = 'PAN',
  PAPUA_NEW_GUINEA = 'PNG',
  PARAGUAY = 'PRY',
  PERU = 'PER',
  PHILIPPINES = 'PHL',
  PITCAIRN = 'PCN',
  POLAND = 'POL',
  PORTUGAL = 'PRT',
  PUERTO_RICO = 'PRI',
  QATAR = 'QAT',
  ROMANIA = 'ROU',
  RUSSIAN_FEDERATION = 'RUS',
  RWANDA = 'RWA',
  REUNION = 'REU',
  SAINT_BARTHELEMY = 'BLM',
  SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = 'SHN',
  SAINT_KITTS_AND_NEVIS = 'KNA',
  SAINT_LUCIA = 'LCA',
  SAINT_MARTIN_FRENCH_PART = 'MAF',
  SAINT_PIERRE_AND_MIQUELON = 'SPM',
  SAINT_VINCENT_AND_THE_GRENADINES = 'VCT',
  SAMOA = 'WSM',
  SAN_MARINO = 'SMR',
  SAO_TOME_AND_PRINCIPE = 'STP',
  SAUDI_ARABIA = 'SAU',
  SENEGAL = 'SEN',
  SERBIA = 'SRB',
  SEYCHELLES = 'SYC',
  SIERRA_LEONE = 'SLE',
  SINGAPORE = 'SGP',
  SINT_MAARTEN_DUTCH_PART = 'SXM',
  SLOVAKIA = 'SVK',
  SLOVENIA = 'SVN',
  SOLOMON_ISLANDS = 'SLB',
  SOMALIA = 'SOM',
  SOUTH_AFRICA = 'ZAF',
  SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 'SGS',
  SOUTH_SUDAN = 'SSD',
  SPAIN = 'ESP',
  SRI_LANKA = 'LKA',
  SUDAN = 'SDN',
  SURINAME = 'SUR',
  SVALBARD_AND_JAN_MAYEN = 'SJM',
  SWEDEN = 'SWE',
  SWITZERLAND = 'CHE',
  SYRIAN_ARAB_REPUBLIC = 'SYR',
  TAIWAN_PROVINCE_OF_CHINA = 'TWN',
  TAJIKISTAN = 'TJK',
  TANZANIA_UNITED_REPUBLIC_OF = 'TZA',
  THAILAND = 'THA',
  TIMOR_LESTE = 'TLS',
  TOGO = 'TGO',
  TOKELAU = 'TKL',
  TONGA = 'TON',
  TRINIDAD_AND_TOBAGO = 'TTO',
  TUNISIA = 'TUN',
  TURKEY = 'TUR',
  TURKMENISTAN = 'TKM',
  TURKS_AND_CAICOS_ISLANDS = 'TCA',
  TUVALU = 'TUV',
  UGANDA = 'UGA',
  UKRAINE = 'UKR',
  UNITED_ARAB_EMIRATES = 'ARE',
  UNITED_KINGDOM = 'GBR',
  UNITED_STATES = 'USA',
  UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'UMI',
  URUGUAY = 'URY',
  UZBEKISTAN = 'UZB',
  VANUATU = 'VUT',
  VENEZUELA_BOLIVARIAN_REPUBLIC_OF = 'VEN',
  VIET_NAM = 'VNM',
  VIRGIN_ISLANDS_BRITISH = 'VGB',
  VIRGIN_ISLANDS_US = 'VIR',
  WALLIS_AND_FUTUNA = 'WLF',
  WESTERN_SAHARA = 'ESH',
  YEMEN = 'YEM',
  ZAMBIA = 'ZMB',
  ZIMBABWE = 'ZWE',
  ALAND_ISLANDS = 'ALA',
}

export interface Country {
  name_ar: string;
  name_en: string;
  code: string;
}

export const countries: Country[] = [
  { name_ar: 'أفغانستان', name_en: 'Afghanistan', code: CountryCodes.AFGHANISTAN },
  { name_ar: 'ألبانيا', name_en: 'Albania', code: CountryCodes.ALBANIA },
  { name_ar: 'الجزائر', name_en: 'Algeria', code: CountryCodes.ALGERIA },
  { name_ar: 'ساموا الأمريكية', name_en: 'American Samoa', code: CountryCodes.AMERICAN_SAMOA },
  { name_ar: 'أندورا', name_en: 'Andorra', code: CountryCodes.ANDORRA },
  { name_ar: 'أنغولا', name_en: 'Angola', code: CountryCodes.ANGOLA },
  { name_ar: 'أنغيلا', name_en: 'Anguilla', code: CountryCodes.ANGUILLA },
  { name_ar: 'القارة القطبية الجنوبية', name_en: 'Antarctica', code: CountryCodes.ANTARCTICA },
  {
    name_ar: 'أنتيغوا وبربودا',
    name_en: 'Antigua and Barbuda',
    code: CountryCodes.ANTIGUA_AND_BARBUDA,
  },
  { name_ar: 'الأرجنتين', name_en: 'Argentina', code: CountryCodes.ARGENTINA },
  { name_ar: 'أرمينيا', name_en: 'Armenia', code: CountryCodes.ARMENIA },
  { name_ar: 'أروبا', name_en: 'Aruba', code: CountryCodes.ARUBA },
  { name_ar: 'أستراليا', name_en: 'Australia', code: CountryCodes.AUSTRALIA },
  { name_ar: 'النمسا', name_en: 'Austria', code: CountryCodes.AUSTRIA },
  { name_ar: 'أذربيجان', name_en: 'Azerbaijan', code: CountryCodes.AZERBAIJAN },
  { name_ar: 'البهاما', name_en: 'Bahamas', code: CountryCodes.BAHAMAS },
  { name_ar: 'البحرين', name_en: 'Bahrain', code: CountryCodes.BAHRAIN },
  { name_ar: 'بنغلاديش', name_en: 'Bangladesh', code: CountryCodes.BANGLADESH },
  { name_ar: 'بربادوس', name_en: 'Barbados', code: CountryCodes.BARBADOS },
  { name_ar: 'بيلاروس', name_en: 'Belarus', code: CountryCodes.BELARUS },
  { name_ar: 'بلجيكا', name_en: 'Belgium', code: CountryCodes.BELGIUM },
  { name_ar: 'بليز', name_en: 'Belize', code: CountryCodes.BELIZE },
  { name_ar: 'بنين', name_en: 'Benin', code: CountryCodes.BENIN },
  { name_ar: 'برمودا', name_en: 'Bermuda', code: CountryCodes.BERMUDA },
  { name_ar: 'بوتان', name_en: 'Bhutan', code: CountryCodes.BHUTAN },
  { name_ar: 'بوليفيا', name_en: 'Bolivia', code: CountryCodes.BOLIVIA_PLURINATIONAL_STATE_OF },
  { name_ar: 'البرازيل', name_en: 'Brazil', code: CountryCodes.BRAZIL },
  { name_ar: 'بروناي', name_en: 'Brunei Darussalam', code: CountryCodes.BRUNEI_DARUSSALAM },
  { name_ar: 'بلغاريا', name_en: 'Bulgaria', code: CountryCodes.BULGARIA },
  { name_ar: 'بوركينا فاسو', name_en: 'Burkina Faso', code: CountryCodes.BURKINA_FASO },
  { name_ar: 'بوروندي', name_en: 'Burundi', code: CountryCodes.BURUNDI },
  { name_ar: 'الرأس الأخضر', name_en: 'Cabo Verde', code: CountryCodes.CABO_VERDE },
  { name_ar: 'كمبوديا', name_en: 'Cambodia', code: CountryCodes.CAMBODIA },
  { name_ar: 'الكاميرون', name_en: 'Cameroon', code: CountryCodes.CAMEROON },
  { name_ar: 'كندا', name_en: 'Canada', code: CountryCodes.CANADA },
  { name_ar: 'جزر كايمان', name_en: 'Cayman Islands', code: CountryCodes.CAYMAN_ISLANDS },
  {
    name_ar: 'جمهورية أفريقيا الوسطى',
    name_en: 'Central African Republic',
    code: CountryCodes.CENTRAL_AFRICAN_REPUBLIC,
  },
  { name_ar: 'تشاد', name_en: 'Chad', code: CountryCodes.CHAD },
  { name_ar: 'تشيلي', name_en: 'Chile', code: CountryCodes.CHILE },
  { name_ar: 'الصين', name_en: 'China', code: CountryCodes.CHINA },
  { name_ar: 'كولومبيا', name_en: 'Colombia', code: CountryCodes.COLOMBIA },
  { name_ar: 'جزر القمر', name_en: 'Comoros', code: CountryCodes.COMOROS },
  { name_ar: 'الكونغو', name_en: 'Congo', code: CountryCodes.CONGO },
  { name_ar: 'كوستاريكا', name_en: 'Costa Rica', code: CountryCodes.COSTA_RICA },
  { name_ar: 'كرواتيا', name_en: 'Croatia', code: CountryCodes.CROATIA },
  { name_ar: 'كوبا', name_en: 'Cuba', code: CountryCodes.CUBA },
  { name_ar: 'قبرص', name_en: 'Cyprus', code: CountryCodes.CYPRUS },
  { name_ar: 'التشيك', name_en: 'Czechia', code: CountryCodes.CZECHIA },
  { name_ar: 'ساحل العاج', name_en: "Côte d'Ivoire", code: CountryCodes.COTE_DIVOIRE },
  { name_ar: 'الدنمارك', name_en: 'Denmark', code: CountryCodes.DENMARK },
  { name_ar: 'جيبوتي', name_en: 'Djibouti', code: CountryCodes.DJIBOUTI },
  { name_ar: 'دومينيكا', name_en: 'Dominica', code: CountryCodes.DOMINICA },
  {
    name_ar: 'جمهورية الدومينيكان',
    name_en: 'Dominican Republic',
    code: CountryCodes.DOMINICAN_REPUBLIC,
  },
  { name_ar: 'الإكوادور', name_en: 'Ecuador', code: CountryCodes.ECUADOR },
  { name_ar: 'مصر', name_en: 'Egypt', code: CountryCodes.EGYPT },
  { name_ar: 'السلفادور', name_en: 'El Salvador', code: CountryCodes.EL_SALVADOR },
  {
    name_ar: 'غينيا الاستوائية',
    name_en: 'Equatorial Guinea',
    code: CountryCodes.EQUATORIAL_GUINEA,
  },
  { name_ar: 'إريتريا', name_en: 'Eritrea', code: CountryCodes.ERITREA },
  { name_ar: 'إستونيا', name_en: 'Estonia', code: CountryCodes.ESTONIA },
  { name_ar: 'إثيوبيا', name_en: 'Ethiopia', code: CountryCodes.ETHIOPIA },
  { name_ar: 'فيجي', name_en: 'Fiji', code: CountryCodes.FIJI },
  { name_ar: 'فنلندا', name_en: 'Finland', code: CountryCodes.FINLAND },
  { name_ar: 'فرنسا', name_en: 'France', code: CountryCodes.FRANCE },
  { name_ar: 'الغابون', name_en: 'Gabon', code: CountryCodes.GABON },
  { name_ar: 'غامبيا', name_en: 'Gambia', code: CountryCodes.GAMBIA },
  { name_ar: 'جورجيا', name_en: 'Georgia', code: CountryCodes.GEORGIA },
  { name_ar: 'ألمانيا', name_en: 'Germany', code: CountryCodes.GERMANY },
  { name_ar: 'غانا', name_en: 'Ghana', code: CountryCodes.GHANA },
  { name_ar: 'اليونان', name_en: 'Greece', code: CountryCodes.GREECE },
  { name_ar: 'غرينادا', name_en: 'Grenada', code: CountryCodes.GRENADA },
  { name_ar: 'غواتيمالا', name_en: 'Guatemala', code: CountryCodes.GUATEMALA },
  { name_ar: 'غينيا', name_en: 'Guinea', code: CountryCodes.GUINEA },
  { name_ar: 'غينيا بيساو', name_en: 'Guinea-Bissau', code: CountryCodes.GUINEA_BISSAU },
  { name_ar: 'غيانا', name_en: 'Guyana', code: CountryCodes.GUYANA },
  { name_ar: 'هايتي', name_en: 'Haiti', code: CountryCodes.HAITI },
  { name_ar: 'هندوراس', name_en: 'Honduras', code: CountryCodes.HONDURAS },
  { name_ar: 'هونغ كونغ', name_en: 'Hong Kong', code: CountryCodes.HONG_KONG },
  { name_ar: 'المجر', name_en: 'Hungary', code: CountryCodes.HUNGARY },
  { name_ar: 'آيسلندا', name_en: 'Iceland', code: CountryCodes.ICELAND },
  { name_ar: 'الهند', name_en: 'India', code: CountryCodes.INDIA },
  { name_ar: 'إندونيسيا', name_en: 'Indonesia', code: CountryCodes.INDONESIA },
  { name_ar: 'إيران', name_en: 'Iran', code: CountryCodes.IRAN_ISLAMIC_REPUBLIC_OF },
  { name_ar: 'العراق', name_en: 'Iraq', code: CountryCodes.IRAQ },
  { name_ar: 'أيرلندا', name_en: 'Ireland', code: CountryCodes.IRELAND },
  { name_ar: 'إسرائيل', name_en: 'Israel', code: CountryCodes.ISRAEL },
  { name_ar: 'إيطاليا', name_en: 'Italy', code: CountryCodes.ITALY },
  { name_ar: 'جامايكا', name_en: 'Jamaica', code: CountryCodes.JAMAICA },
  { name_ar: 'اليابان', name_en: 'Japan', code: CountryCodes.JAPAN },
  { name_ar: 'الأردن', name_en: 'Jordan', code: CountryCodes.JORDAN },
  { name_ar: 'كازاخستان', name_en: 'Kazakhstan', code: CountryCodes.KAZAKHSTAN },
  { name_ar: 'كينيا', name_en: 'Kenya', code: CountryCodes.KENYA },
  { name_ar: 'كيريباتي', name_en: 'Kiribati', code: CountryCodes.KIRIBATI },
  {
    name_ar: 'كوريا الشمالية',
    name_en: 'North Korea',
    code: CountryCodes.KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF,
  },
  { name_ar: 'كوريا الجنوبية', name_en: 'South Korea', code: CountryCodes.KOREA_REPUBLIC_OF },
  { name_ar: 'الكويت', name_en: 'Kuwait', code: CountryCodes.KUWAIT },
  { name_ar: 'قيرغيزستان', name_en: 'Kyrgyzstan', code: CountryCodes.KYRGYZSTAN },
  { name_ar: 'لاوس', name_en: 'Laos', code: CountryCodes.LAO_PEOPLES_DEMOCRATIC_REPUBLIC },
  { name_ar: 'لاتفيا', name_en: 'Latvia', code: CountryCodes.LATVIA },
  { name_ar: 'لبنان', name_en: 'Lebanon', code: CountryCodes.LEBANON },
  { name_ar: 'ليسوتو', name_en: 'Lesotho', code: CountryCodes.LESOTHO },
  { name_ar: 'ليبيريا', name_en: 'Liberia', code: CountryCodes.LIBERIA },
  { name_ar: 'ليبيا', name_en: 'Libya', code: CountryCodes.LIBYA },
  { name_ar: 'ليختنشتاين', name_en: 'Liechtenstein', code: CountryCodes.LIECHTENSTEIN },
  { name_ar: 'ليتوانيا', name_en: 'Lithuania', code: CountryCodes.LITHUANIA },
  { name_ar: 'لوكسمبورغ', name_en: 'Luxembourg', code: CountryCodes.LUXEMBOURG },
  { name_ar: 'ماكاو', name_en: 'Macao', code: CountryCodes.MACAO },
  { name_ar: 'مدغشقر', name_en: 'Madagascar', code: CountryCodes.MADAGASCAR },
  { name_ar: 'مالاوي', name_en: 'Malawi', code: CountryCodes.MALAWI },
  { name_ar: 'ماليزيا', name_en: 'Malaysia', code: CountryCodes.MALAYSIA },
  { name_ar: 'جزر المالديف', name_en: 'Maldives', code: CountryCodes.MALDIVES },
  { name_ar: 'مالي', name_en: 'Mali', code: CountryCodes.MALI },
  { name_ar: 'مالطا', name_en: 'Malta', code: CountryCodes.MALTA },
  { name_ar: 'جزر مارشال', name_en: 'Marshall Islands', code: CountryCodes.MARSHALL_ISLANDS },
  { name_ar: 'موريتانيا', name_en: 'Mauritania', code: CountryCodes.MAURITANIA },
  { name_ar: 'موريشيوس', name_en: 'Mauritius', code: CountryCodes.MAURITIUS },
  { name_ar: 'المكسيك', name_en: 'Mexico', code: CountryCodes.MEXICO },
  { name_ar: 'مولدوفا', name_en: 'Moldova', code: CountryCodes.MONACO },
  { name_ar: 'منغوليا', name_en: 'Mongolia', code: CountryCodes.MONGOLIA },
  { name_ar: 'الجبل الأسود', name_en: 'Montenegro', code: CountryCodes.MONTENEGRO },
  { name_ar: 'المغرب', name_en: 'Morocco', code: CountryCodes.MOROCCO },
  { name_ar: 'موزمبيق', name_en: 'Mozambique', code: CountryCodes.MOZAMBIQUE },
  { name_ar: 'ميانمار', name_en: 'Myanmar', code: CountryCodes.MYANMAR },
  { name_ar: 'ناميبيا', name_en: 'Namibia', code: CountryCodes.NAMIBIA },
  { name_ar: 'ناورو', name_en: 'Nauru', code: CountryCodes.NAURU },
  { name_ar: 'نيبال', name_en: 'Nepal', code: CountryCodes.NEPAL },
  { name_ar: 'هولندا', name_en: 'Netherlands', code: CountryCodes.NETHERLANDS },
  { name_ar: 'نيوزيلندا', name_en: 'New Zealand', code: CountryCodes.NEW_ZEALAND },
  { name_ar: 'نيكاراغوا', name_en: 'Nicaragua', code: CountryCodes.NICARAGUA },
  { name_ar: 'النيجر', name_en: 'Niger', code: CountryCodes.NIGER },
  { name_ar: 'نيجيريا', name_en: 'Nigeria', code: CountryCodes.NIGERIA },
  { name_ar: 'مقدونيا الشمالية', name_en: 'North Macedonia', code: CountryCodes.NORTH_MACEDONIA },
  { name_ar: 'النرويج', name_en: 'Norway', code: CountryCodes.NORWAY },
  { name_ar: 'عُمان', name_en: 'Oman', code: CountryCodes.OMAN },
  { name_ar: 'باكستان', name_en: 'Pakistan', code: CountryCodes.PAKISTAN },
  { name_ar: 'بالاو', name_en: 'Palau', code: CountryCodes.PALAU },
  { name_ar: 'فلسطين', name_en: 'Palestine', code: CountryCodes.PALESTINE_STATE_OF },
  { name_ar: 'بنما', name_en: 'Panama', code: CountryCodes.PANAMA },
  {
    name_ar: 'بابوا غينيا الجديدة',
    name_en: 'Papua New Guinea',
    code: CountryCodes.PAPUA_NEW_GUINEA,
  },
  { name_ar: 'باراغواي', name_en: 'Paraguay', code: CountryCodes.PARAGUAY },
  { name_ar: 'بيرو', name_en: 'Peru', code: CountryCodes.PERU },
  { name_ar: 'الفلبين', name_en: 'Philippines', code: CountryCodes.PHILIPPINES },
  { name_ar: 'بولندا', name_en: 'Poland', code: CountryCodes.POLAND },
  { name_ar: 'البرتغال', name_en: 'Portugal', code: CountryCodes.PORTUGAL },
  { name_ar: 'بورتوريكو', name_en: 'Puerto Rico', code: CountryCodes.PUERTO_RICO },
  { name_ar: 'قطر', name_en: 'Qatar', code: CountryCodes.QATAR },
  { name_ar: 'رومانيا', name_en: 'Romania', code: CountryCodes.ROMANIA },
  { name_ar: 'روسيا', name_en: 'Russian Federation', code: CountryCodes.RUSSIAN_FEDERATION },
  { name_ar: 'رواندا', name_en: 'Rwanda', code: CountryCodes.RWANDA },
  { name_ar: 'ساموا', name_en: 'Samoa', code: CountryCodes.SAMOA },
  { name_ar: 'سان مارينو', name_en: 'San Marino', code: CountryCodes.SAN_MARINO },
  {
    name_ar: 'ساو تومي وبرينسيبي',
    name_en: 'Sao Tome and Principe',
    code: CountryCodes.SAO_TOME_AND_PRINCIPE,
  },
  { name_ar: 'المملكة العربية السعودية', name_en: 'Saudi Arabia', code: CountryCodes.SAUDI_ARABIA },
  { name_ar: 'السنغال', name_en: 'Senegal', code: CountryCodes.SENEGAL },
  { name_ar: 'صربيا', name_en: 'Serbia', code: CountryCodes.SERBIA },
  { name_ar: 'سيشل', name_en: 'Seychelles', code: CountryCodes.SEYCHELLES },
  { name_ar: 'سيراليون', name_en: 'Sierra Leone', code: CountryCodes.SIERRA_LEONE },
  { name_ar: 'سنغافورة', name_en: 'Singapore', code: CountryCodes.SINGAPORE },
  { name_ar: 'سلوفاكيا', name_en: 'Slovakia', code: CountryCodes.SLOVAKIA },
  { name_ar: 'سلوفينيا', name_en: 'Slovenia', code: CountryCodes.SLOVENIA },
  { name_ar: 'جزر سليمان', name_en: 'Solomon Islands', code: CountryCodes.SOLOMON_ISLANDS },
  { name_ar: 'الصومال', name_en: 'Somalia', code: CountryCodes.SOMALIA },
  { name_ar: 'جنوب أفريقيا', name_en: 'South Africa', code: CountryCodes.SOUTH_AFRICA },
  { name_ar: 'جنوب السودان', name_en: 'South Sudan', code: CountryCodes.SOUTH_SUDAN },
  { name_ar: 'إسبانيا', name_en: 'Spain', code: CountryCodes.SPAIN },
  { name_ar: 'سريلانكا', name_en: 'Sri Lanka', code: CountryCodes.SRI_LANKA },
  { name_ar: 'السودان', name_en: 'Sudan', code: CountryCodes.SUDAN },
  { name_ar: 'سورينام', name_en: 'Suriname', code: CountryCodes.SURINAME },
  { name_ar: 'السويد', name_en: 'Sweden', code: CountryCodes.SWEDEN },
  { name_ar: 'سويسرا', name_en: 'Switzerland', code: CountryCodes.SWITZERLAND },
  { name_ar: 'سوريا', name_en: 'Syrian Arab Republic', code: CountryCodes.SYRIAN_ARAB_REPUBLIC },
  { name_ar: 'تايوان', name_en: 'Taiwan', code: CountryCodes.TAIWAN_PROVINCE_OF_CHINA },
  { name_ar: 'طاجيكستان', name_en: 'Tajikistan', code: CountryCodes.TAJIKISTAN },
  { name_ar: 'تنزانيا', name_en: 'Tanzania', code: CountryCodes.TANZANIA_UNITED_REPUBLIC_OF },
  { name_ar: 'تايلاند', name_en: 'Thailand', code: CountryCodes.THAILAND },
  { name_ar: 'تيمور الشرقية', name_en: 'Timor-Leste', code: CountryCodes.TIMOR_LESTE },
  { name_ar: 'توغو', name_en: 'Togo', code: CountryCodes.TOGO },
  { name_ar: 'تونغا', name_en: 'Tonga', code: CountryCodes.TONGA },
  {
    name_ar: 'ترينيداد وتوباغو',
    name_en: 'Trinidad and Tobago',
    code: CountryCodes.TRINIDAD_AND_TOBAGO,
  },
  { name_ar: 'تونس', name_en: 'Tunisia', code: CountryCodes.TUNISIA },
  { name_ar: 'تركيا', name_en: 'Turkey', code: CountryCodes.TURKEY },
  { name_ar: 'تركمانستان', name_en: 'Turkmenistan', code: CountryCodes.TURKMENISTAN },
  { name_ar: 'توفالو', name_en: 'Tuvalu', code: CountryCodes.TUVALU },
  { name_ar: 'أوغندا', name_en: 'Uganda', code: CountryCodes.UGANDA },
  { name_ar: 'أوكرانيا', name_en: 'Ukraine', code: CountryCodes.UKRAINE },
  {
    name_ar: 'الإمارات العربية المتحدة',
    name_en: 'United Arab Emirates',
    code: CountryCodes.UNITED_ARAB_EMIRATES,
  },
  { name_ar: 'المملكة المتحدة', name_en: 'United Kingdom', code: CountryCodes.UNITED_KINGDOM },
  {
    name_ar: 'الولايات المتحدة الأمريكية',
    name_en: 'United States',
    code: CountryCodes.UNITED_STATES,
  },
  { name_ar: 'أوروغواي', name_en: 'Uruguay', code: CountryCodes.URUGUAY },
  { name_ar: 'أوزبكستان', name_en: 'Uzbekistan', code: CountryCodes.UZBEKISTAN },
  { name_ar: 'فانواتو', name_en: 'Vanuatu', code: CountryCodes.VANUATU },
  { name_ar: 'فنزويلا', name_en: 'Venezuela', code: CountryCodes.VENEZUELA_BOLIVARIAN_REPUBLIC_OF },
  { name_ar: 'فيتنام', name_en: 'Viet Nam', code: CountryCodes.VIET_NAM },
  { name_ar: 'اليمن', name_en: 'Yemen', code: CountryCodes.YEMEN },
  { name_ar: 'زامبيا', name_en: 'Zambia', code: CountryCodes.ZAMBIA },
  { name_ar: 'زيمبابوي', name_en: 'Zimbabwe', code: CountryCodes.ZIMBABWE },
];
